### ISSUE TITLE
Broken for dmd 2.080.1

### ISSUE THREAD

**Issue by belka-ew** [dlang-community/experimental.xml#22]
> Performing "debug" build using /usr/bin/dmd for x86_64.
> std-experimental-xml 0.1.5+commit.2.g4cd291b: building configuration "library"...
> source/std/experimental/xml/cursor.d(562,45): Warning: C preprocessor directive #REQUIRED is not supported
> source/std/experimental/xml/parser.d(488,45): Warning: C preprocessor directive #REQUIRED is not supported
> source/std/experimental/xml/lexers.d(769,24): Error: template std.experimental.xml.lexers.chooseLexer cannot deduce function from argument types !(string, cast(Flag)true, shared(GCAllocator))(shared(const(GCAllocator)), void function() @system), candidates are:
> source/std/experimental/xml/lexers.d(727,6):        std.experimental.xml.lexers.chooseLexer(Input, Flag reuseBuffer = Yes.reuseBuffer, Alloc, Handler)(ref Alloc alloc, Handler handler)
> source/std/experimental/xml/lexers.d(751,6):        std.experimental.xml.lexers.chooseLexer(Input, Alloc = shared(GCAllocator), Flag reuseBuffer = Yes.reuseBuffer, Handler)(Handler handler) if (is(typeof(Alloc.instance)) && isSomeFunction!handler)
> source/std/experimental/xml/lexers.d(758,6):        std.experimental.xml.lexers.chooseLexer(Input, Flag reuseBuffer = Yes.reuseBuffer, Alloc)(ref Alloc alloc) if (!isSomeFunction!alloc)
> source/std/experimental/xml/lexers.d(765,6):        std.experimental.xml.lexers.chooseLexer(Input, Alloc = shared(GCAllocator), Flag reuseBuffer = Yes.reuseBuffer)() if (is(typeof(Alloc.instance)))
> source/std/experimental/xml/lexers.d(776,47): Error: template instance `std.experimental.xml.lexers.chooseLexer!(string, shared(GCAllocator), cast(Flag)true)` error instantiating
> source/std/experimental/xml/legacy.d(21,41):        instantiated from here: lexer!string
> source/std/experimental/xml/legacy.d(111,16): Error: undefined identifier CursorType
> /usr/bin/dmd failed with exit code 1.

**Comment by rikkimax** [comment]
Nobody updated this project to use the RCAllocator. It won't work above 2.079.
I'm strongly considering dxml for myself, over this considering how much work it needs done on it.

**Comment by wilzbach** [comment]
You could just swap in stdx-allocator for now.

**Comment by wilzbach** [comment]
If you feel that this project is important, we could also add it to the project tester...
