### ISSUE TITLE
Error: module `std.traits` member `AliasSeq` is not visible from module `domimpl`

### ISSUE THREAD

**Issue by shoo** [dlang-community/experimental.xml#28]
https://github.com/dlang-community/experimental.xml/blob/740bb6b05225a800b88cbffee33d0c1403f73a61/source/std/experimental/xml/domimpl.d#L174

This code invalid in dmd 2.097.0.
Use `import std.meta: AliasSeq;` instead.

**Comment by burner** [comment]
https://github.com/dlang-community/experimental.xml/pull/29
